In [1]:
import numpy as np 
import pandas as pd
from sklearn import datasets
from GBDT.Gradientboost import GradientBoostClassifier

In [2]:
train_df = pd.read_csv('./titanic/train.csv').fillna(0)
test_df = pd.read_csv('./titanic/test.csv').fillna(0)
#, 'SibSp', 'Parch'
categorical_columns = ['Pclass', 'Sex', 'Embarked']
numerical_columns = ['Age', 'Fare']
drop_columns = ['PassengerId', 'Survived', 'Name', 'Ticket', 'Cabin']
drop_columns1 = ['PassengerId', 'Name', 'Ticket', 'Cabin']

train_df = pd.get_dummies(train_df, columns=categorical_columns, drop_first=True)
test_df = pd.get_dummies(test_df, columns=categorical_columns, drop_first=True)

x_train = train_df.drop(columns=drop_columns, axis=1).values
y_train = train_df.Survived.values
# x_test = test_df.drop(columns=drop_columns1, axis=1).values
# y_test = test_df.Survived.values

In [3]:
Gbdt = GradientBoostClassifier(n_estimators=50, learning_rate=0.5, max_depth=5)
Gbdt.fit(x_train[0:200], y_train[0:200])

In [4]:
print(Gbdt.train_score, Gbdt.score(x_train[200:600], y_train[200:600]))

0.875 0.77


D:\Projects\Python\GBDT-project\GBDT\Gradientboost.py:93: ComplexWarning: Casting complex values to real discards the imaginary part
  f_m_estimator[i+1][x] += self.learning_rate * self.estimator_[i].root.get_predict_value(X[x])


In [5]:
Gbdt.feature_importance

array([1.40613207, 0.8099769 , 0.38037573, 1.11121843, 0.66874729,
       0.63363033, 0.43552992, 0.41491995, 0.21119521, 0.33815761])

# Multi-Classifier

In [6]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target
indices = np.array(range(len(y)))
np.random.shuffle(indices)

xt = X[indices]
yt = y[indices]

In [7]:
Gbdt2 = GradientBoostClassifier()
Gbdt2.fit(xt[0:120], yt[0:120])
Gbdt2.train_score

1.0

In [8]:
Gbdt2.score(xt[120:150], yt[120:150])

0.9333333333333333

In [9]:
Gbdt2.predict(xt[120:150]), yt[120:150]

(array([2, 1, 2, 0, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1,
        2, 0, 2, 2, 2, 0, 0, 1], dtype=int64),
 array([1, 1, 2, 0, 2, 2, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1,
        1, 0, 2, 2, 2, 0, 0, 1]))

In [10]:
Gbdt2.feature_importance

array([[1.16474751, 0.60684929, 1.51577107, 1.46793299],
       [1.01293217, 0.47861511, 1.38699012, 1.26818668],
       [1.09916766, 0.54423767, 1.42829072, 1.39028839]])