In [1]:
import numpy as np 
# Load libraries
from sklearn import metrics
from sklearn import datasets
from sklearn.tree import _tree
from sklearn.tree.export import export_text
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from GBDT.Gradientboost import GradientBoostClassifier

C:\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.tree.export module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
x = np.array([[1, 5, 20], [2, 7, 30], [3, 21, 70], [4, 30, 60]])
y = np.array([0, 0, 1, 1])
xt = np.array([[5, 25, 65]])

Gbdt = GradientBoostClassifier()
Gbdt.fit(x, y)
pred = Gbdt.predict(x)
prob = Gbdt.predict_proba(x)
# print(pred, prob)

D:\Projects\Python\GBDT-project\GBDT\Gradientboost.py:93: ComplexWarning: Casting complex values to real discards the imaginary part
  f_m_estimator[i+1][x] += self.learning_rate * self.estimator_[i].root.get_predict_value(X[x])


In [3]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [4]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test
Gbdt2 = GradientBoostClassifier()
Gbdt2.fit(X_train, y_train)
pred = Gbdt.predict(X_train)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
# Create adaboost classifer object
abc = GradientBoostingClassifier(n_estimators=50,
                         learning_rate=1)
# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)

In [6]:
np.unique(y_train)
y_train[y_train == 1]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9333333333333333


In [8]:
dt_stump=DecisionTreeClassifier(max_depth=1,min_samples_leaf=1)
dt_stump.fit(X_train,y_train)
dt_stump.predict(X_train)

tree_ = dt_stump.tree_
leaves = np.where(tree_.children_left == _tree.TREE_LEAF)[0]
for leaf in np.where(tree_.children_left == _tree.TREE_LEAF)[0]:
    print(leaf)
leaves

1
2


array([1, 2], dtype=int64)